workspace 'TeamTalk.xcworkspace'

target 'TeamTalk' do
  platform :ios, '7.0'

  pod 'FMDB', '~> 2.3'
  pod 'SDWebImage', '~> 3.6'
  pod 'AFNetworking', '~> 2.3.0'
  pod 'DACircularProgress', '~> 2.2.0'
  pod 'MBProgressHUD', '~> 0.8'
  pod 'PSTCollectionView', '~> 1.2.1'
  pod 'HPGrowingTextView', '~> 1.1'
  pod 'ProtocolBuffers', '~> 1.9.4'
  pod 'SCLAlertView-Objective-C', '~> 0.7.3'
  pod 'MWPhotoBrowser'
  pod 'Masonry'
  pod 'TTTAttributedLabel'
  pod 'SVWebViewController'
  pod 'XHImageViewer'
  pod 'ZXingObjC'
end

# Xcode 26 默认把一批告警当错误（-Werror=return-type / deprecated-objc-isa-usage
# / objc-root-class / implicit-function-declaration / non-modular-include 等），
# 本项目依赖的都是 2013~2015 年的老 pod，无法在新编译器下满足这些约束，
# 统一降级为普通告警，保证老代码可编译。
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      config.build_settings['CLANG_WARN_DEPRECATED_OBJC_ISA_USAGE'] = 'NO'
      config.build_settings['CLANG_WARN_OBJC_ROOT_CLASS'] = 'NO'
      config.build_settings['GCC_WARN_ABOUT_RETURN_TYPE'] = 'NO'
      config.build_settings['OTHER_CFLAGS'] = '$(inherited) -Wno-error=return-type -Wno-error=implicit-function-declaration -Wno-error=deprecated-objc-isa-usage -Wno-error=objc-root-class -Wno-error=non-modular-include-in-framework-module'
    end
  end

  # Xcode 26 SDK 的 UICollectionView / UIDiffableDataSource 与老 pod 的
  # PSTCollectionViewData 都有 numberOfItemsInSection: 等方法，id 类型接收者
  # 调用时 clang 无法消歧（硬错误，-Wno-error 无效）。
  # 把字典取出的 id 显式转换为 PSTCollectionViewData *。
  pst_m = File.join(installer.sandbox.root, 'PSTCollectionView/PSTCollectionView/PSTCollectionView.m')
  if File.exist?(pst_m)
    src = File.read(pst_m)
    src = src.gsub('[_update[@"oldModel"]', '[(PSTCollectionViewData *)_update[@"oldModel"]')
    src = src.gsub('[_update[@"newModel"]', '[(PSTCollectionViewData *)_update[@"newModel"]')
    File.write(pst_m, src)
    puts 'patched PSTCollectionView.m for Xcode 26 method ambiguity'
  end
end
